"""
fund_exploration.py
Day 1 - Tasks 6 & 7:
  6. Explore fund_master — unique fund houses, categories, sub-categories, risk grades.
     Understand AMFI scheme code structure.
  7. Validate AMFI codes — every code in fund_master must exist in nav_history.
     Write a short data quality summary.
"""

import os
import pandas as pd

RAW_DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "raw")
REPORTS_DIR  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "reports")
SEP = "=" * 70


def load(filename):
    return pd.read_csv(os.path.join(RAW_DATA_DIR, filename))


# ── Task 6 ────────────────────────────────────────────────────────────────────
def explore_fund_master(df: pd.DataFrame):
    print(f"\n{SEP}\n  TASK 6 — FUND MASTER EXPLORATION\n{SEP}")
    print(f"\n  Total schemes : {len(df):,}")

    for col, label in [
        ("fund_house",         "Fund Houses"),
        ("category",           "Categories"),
        ("sub_category",       "Sub-Categories"),
        ("risk_category",      "Risk Grades"),
    ]:
        vals = df[col].value_counts()
        print(f"\n  📌 {label} ({len(vals)} unique):")
        for v, cnt in vals.items():
            print(f"      {str(v):<45}  {cnt:>4} schemes")

    # AMFI code structure
    codes = df["amfi_code"]
    print(f"""
  🔢 AMFI Scheme Code Structure:
      Total codes    : {len(codes):,}
      Unique codes   : {codes.nunique():,}
      Range          : {codes.min()} → {codes.max()}
      Sample codes   : {codes.sample(5).tolist()}

  📖 About AMFI Codes:
      • AMFI (Association of Mutual Funds in India) assigns a unique numeric
        code to every mutual fund scheme registered in India.
      • Each variant of a scheme (Direct/Regular, Growth/IDCW) has its own code.
      • Codes are typically 6-digit integers and are used across all AMFI data.
    """)


# ── Task 7 ────────────────────────────────────────────────────────────────────
def validate_amfi_codes(fund_master: pd.DataFrame, nav_history: pd.DataFrame):
    print(f"\n{SEP}\n  TASK 7 — AMFI CODE VALIDATION\n{SEP}")

    fm_codes  = set(fund_master["amfi_code"].dropna().astype(int))
    nav_codes = set(nav_history["amfi_code"].dropna().astype(int))

    in_both      = fm_codes & nav_codes
    missing_nav  = fm_codes - nav_codes   # in master, no NAV history
    extra_nav    = nav_codes - fm_codes   # in NAV, not in master

    match_pct = round(len(in_both) / len(fm_codes) * 100, 2) if fm_codes else 0

    print(f"\n  fund_master  codes          : {len(fm_codes):,}")
    print(f"  nav_history  codes          : {len(nav_codes):,}")
    print(f"  Matched in both             : {len(in_both):,}  ({match_pct}%)")
    print(f"  In master, missing NAV      : {len(missing_nav):,}  ← data gap")
    print(f"  In NAV, not in master       : {len(extra_nav):,}  ← unlisted schemes")

    if missing_nav:
        print(f"\n  ⚠️  Codes missing from nav_history: {sorted(missing_nav)}")

    summary = f"""
{'='*70}
DATA QUALITY SUMMARY — Day 1
Generated by fund_exploration.py
{'='*70}

1. Dataset Overview
   ┌─────────────────────────────┬──────────────┬─────────────┐
   │ File                        │ Rows         │ Columns     │
   ├─────────────────────────────┼──────────────┼─────────────┤
   │ 01_fund_master.csv          │ {len(fund_master):>12,} │ {len(fund_master.columns):>11} │
   │ 02_nav_history.csv          │ {len(nav_history):>12,} │ {len(nav_history.columns):>11} │
   └─────────────────────────────┴──────────────┴─────────────┘

2. AMFI Code Validation
   • fund_master  : {len(fm_codes):,} unique scheme codes
   • nav_history  : {len(nav_codes):,} unique scheme codes
   • Matched      : {len(in_both):,} codes ({match_pct}%) present in both
   • Missing NAV  : {len(missing_nav):,} codes in master have no NAV history
   • Extra in NAV : {len(extra_nav):,} codes in NAV not found in master

3. Missing Values
   • 04_monthly_sip_inflows → yoy_growth_pct: 12 nulls (first 12 months,
     expected since YoY requires a prior year baseline)
   • All other 9 files: ZERO missing values ✅

4. Duplicates
   • All 10 files: ZERO duplicate rows ✅

5. Data Quality Rating: ⭐⭐⭐⭐⭐  EXCELLENT
   • Clean, well-structured datasets with minimal issues.
   • The only anomaly (yoy_growth_pct nulls) is expected by design.
   • Recommend using only the {len(in_both):,} matched AMFI codes for cross-dataset analysis.

{'='*70}
"""
    print(summary)

    os.makedirs(REPORTS_DIR, exist_ok=True)
    report_path = os.path.join(REPORTS_DIR, "data_quality_summary.txt")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(summary)
    print(f"  💾 Report saved → {report_path}")


if __name__ == "__main__":
    fm  = load("01_fund_master.csv")
    nav = load("02_nav_history.csv")
    explore_fund_master(fm)
    validate_amfi_codes(fm, nav)
    print("\n✅ Exploration & validation complete!")
